spring:
  jackson:
    mapper:
      # 대소문자 상관없게 해주는 옵션
      accept-case-insensitive-enums: true

  datasource:
    url: ${DB_URL}
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${AUTH_ID}
            client-secret: ${AUTH_SECRET}
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: ${AUTH_URI}
            scope: profile_nickname
            client-authentication-method: client_secret_post
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  cloud:
    gcp:
      project-id: ${GCP_PROJECT_ID}
      credentials:
        location: ${GCP_CREDENTIALS_LOCATION}
      storage:
        enabled: true

gcp:
  storage:
    bucket: ${GCP_STORAGE_BUCKET}
jwt:
  secret: ${JWT_SECRET}
stt:
  server:
    url: ${STT_SERVER_URL}

shopping:
  server:
    url: ${SHOPPING_SERVER_URL}